logEntrySchema = {
    "logName": "sorted",
    "resource": "text",
    "timestamp": "int",
    "receiveTimestamp": "int",
    "severity": "keyword",
    "insertId": "sorted",
    "httpRequest": "text",
    "labels": "text",
    "metadata": "text",
    "operation": "text",
    "trace": "sorted",
    "spanId": "sorted",
    "traceSampled": "sorted",
    "sourceLocation": "text",
    "protoPayload": "text",
    "textPayload": "text",
    "jsonPayload": "text",
}